version: '3'
services:
  server:
    container_name: goop-house-submissions
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      goop:
        - external: true
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - SESSION_SECRET=${SESSION_SECRET}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./uploads:/usr/src/app/uploads
  redis:
    networks:
      goop:
        - external: true
    container_name: goop-house-redis
    image: redis
    ports:
      - "6379:6379"